### PR TITLE
feat(data-grid): added disableRowSelectionWithClick option

### PR DESCRIPTION
**Pull request by nckenn**
I think it's better to give an option to disable selection when row-clicking.

### CODE REVIEW

**Comment by nzbin** [comment]
Thanks for your PR, I don't quite understand this feature. The data grid can't select row with row-clicking by default, and you can use the `multiSelectionWithClick` to enable it.

**Comment by nckenn** [comment]
> Thanks for your PR, I don't quite understand this feature. The data grid can't select row with row-clicking by default, and you can use the `multiSelectionWithClick` to enable it.

Basically, what it does is prevent making the checkbox check when row clicking; kindly check the video below. Example scenario: When I click a row, I just want to pop up some modals. By default, when I click a row, it will toggle the select and show the modal, but with this PR, it will prevent toggling the checkbox but only show the modal.

chrome_goekZyzsR3

**Comment by nzbin** [comment]
The new version 15.5.0 has added a new prop `disableRowClickSelection`, please try it.

**Comment by nckenn** [comment]
> The new version 15.5.0 has added a new prop `disableRowClickSelection`, please try it.


Why not merge my request? You can even tell me to adjust it if you want to, anyways thank you. 

PS: i wish you had included also the class "selected" when the row is clicked.

**Pull request closed without merging**
