### PR TITLE
refactor(popover): add left and right positions

### PR DESCRIPTION
**Pull request by JacobBrandt**
Really liked your version of the popover.  So I extended upon it to allow left & right positions of the popover.  Here is my implementation of it.

### CODE REVIEW

**Comment by nzbin** [comment]
Many thanks for your works, but the method is not so good. I will rebuild the popover with 12 positions.

```
+ ------ + ------ +
│                 |
│                 |
+                 +
|                 |
|                 |
+ ------ + ------ +

1. Top left, Top center, Top right
2. Bottom left, Bottom center, Bottom right
3. Left top, Left center, Left bottom
4. Right top, Right center, Right bottom
```

**Comment by JacobBrandt** [comment]
12 positions?  I count 8 as there is no difference between Top left & Left top, etc.  This code handles all 8 positions.

**Comment by JacobBrandt** [comment]
This code handles all positions, did you even try it?

**Comment by shawnvoss** [comment]
I would like this enhancement also. Will you complete the pull request?

**Comment by nzbin** [comment]
@JacobBrandt @shawnvoss 
`v12.2.0` has support left and right positions.

**Pull request closed without merging**
