### PR TITLE
Backport of fix for selected row event / branch 14.8.x

### PR DESCRIPTION
**Pull request by SeymourRu**
Just a simple backport of fix for selected row event for branch 14.8.x

### CODE REVIEW

**Comment by SeymourRu** [comment]
@nzbin sorry to bother you but could you review my PR and release fixed version please? 
Also I am ready to apply this fix to v15-17 too, if it possible.
Thank you in advance!

**Comment by nzbin** [comment]
Thanks for your PR, I'm busy for v18 upgrade now. In fact, the v14 has ended support. Maybe I can publish it when I have enough time.

**Comment by SeymourRu** [comment]
@nzbin no problem, I will wait as much as needed. In mean time will also add PRs for other versions too. I understand that those versions are out of support now but still it is used :)

**Comment by nzbin** [comment]
14.8.5 has released, please have a try.

**Comment by SeymourRu** [comment]
@nzbin Thank you for the release, worked like a charm
I see that you already backported this fix for 15x-17x, thank you for this too :)

**Pull request merged**
