### PR TITLE
feat: add carousel

### PR DESCRIPTION
**Pull request by kharazian**
Hello

I have developed a [carousel component](https://github.com/ng-matero/extensions/issues/225) and I would like to contribute it to the master repository. Could you please guide me on the process for submitting my component? 

Thank you!

### CODE REVIEW

**Comment by nzbin** [comment]
Many thanks for your PR. I won't merge it because its Incomplete functionality compared with 3rd lib.

**Comment by kharazian** [comment]
That's great to hear! I'm glad I could help. Could you please provide more details about the specific functionality or areas that you would like to improve? This will help me to enhance my contribution.

**Comment by palmtreefrb** [comment]
@nzbin  What is "3rd lib" you referenced above?

**Comment by nzbin** [comment]
> @nzbin What is "3rd lib" you referenced above?

https://github.com/ng-matero/extensions/issues/225#issuecomment-1596086932

**Pull request closed without merging**
